<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFNGulBb\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFNGulBb/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFNGulBb.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFNGulBb\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFNGulBb\appAppKernelProdContainer([
    'container.build_hash' => 'FNGulBb',
    'container.build_id' => '4fce805c',
    'container.build_time' => 1710174766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFNGulBb');
