<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3pz4K3n\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3pz4K3n/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container3pz4K3n.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container3pz4K3n\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container3pz4K3n\appAppKernelProdContainer([
    'container.build_hash' => '3pz4K3n',
    'container.build_id' => 'a48a59c8',
    'container.build_time' => 1710255785,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3pz4K3n');
