version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./app:/app
            - ./nginx/certificados:/certificados
            - ./nginx/configuracion.conf.template:/etc/nginx/templates/configuracion.conf.template
        env_file:
            - .env

    meuphp:
        build: php
        volumes:
            - ./app:/app
            - ./php/www.conf:/etc/php/8.2/fpm/pool.d/www.conf

    basedatos:
        image: mysql:8.3
        env_file:
            - .env
        volumes:
            - datos:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d
            - ./db:/backup

    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8000:80
        env_file:
            - .env

volumes:
    datos:
