version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./app:/app
            - ./nginx/certificados:/certificados
            - ./nginx/configuracion.conf.template:/etc/nginx/templates/configuracion.conf.template
        env_file:
            - .env

    meuphp:
        build: php
        volumes:
            - ./app:/app
            - ./php/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
